"""new migration

Revision ID: 3f5e70b9e641
Revises: 
Create Date: 2024-05-27 22:10:38.670802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5e70b9e641'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('категория', sa.Enum('Новичок', 'Любитель', 'Профи', name='категория'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('пол', sa.Enum('М', 'Ж', name='gender_enum'), nullable=False),
    sa.Column('zabeg22', sa.Boolean(), nullable=False),
    sa.Column('zabeg23', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('day_select', sa.Integer(), nullable=False),
    sa.Column('day_distance', sa.Float(), nullable=False),
    sa.Column('day_time', sa.Time(timezone=True), nullable=False),
    sa.Column('day_average_temp', sa.Time(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Time(timezone=True), nullable=False),
    sa.Column('avg_time', sa.Time(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
