"""Initial migration

Revision ID: 673f98aab3d7
Revises: 
Create Date: 2024-05-25 18:52:06.615203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673f98aab3d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_select', sa.Date(), nullable=False),
    sa.Column('day_distance', sa.Float(), nullable=False),
    sa.Column('day_time', sa.Time(timezone=True), nullable=False),
    sa.Column('day_average_temp', sa.Time(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_time', sa.Time(timezone=True), nullable=False),
    sa.Column('avg_time', sa.Time(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner', sa.Integer(), nullable=False),
    sa.Column('runner_category', sa.Integer(), nullable=False),
    sa.Column('runner_gender', sa.String(), nullable=False),
    sa.Column('zabeg22', sa.Boolean(), nullable=False),
    sa.Column('zabeg23', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('statistic')
    op.drop_table('profiles')
    # ### end Alembic commands ###
