"""new migration

Revision ID: aa37f6d35371
Revises: 673f98aab3d7
Create Date: 2024-05-25 18:57:11.765099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa37f6d35371'
down_revision: Union[str, None] = '673f98aab3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('runner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'users', ['runner_id'], ['id'])
    op.add_column('statistic', sa.Column('runner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statistic', 'users', ['runner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistic', type_='foreignkey')
    op.drop_column('statistic', 'runner_id')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'runner_id')
    # ### end Alembic commands ###
